BaseURL = "http://coderzh.github.io/hugo-pacman-theme/"
LanguageCode = "zh-CN"
HasCJKLanguage = true
Title = "Hugo PacMan Theme Demo"
Theme = "hugo-pacman-theme"
pygmentsStyle = "default"
pygmentsUseClasses = true

[Author]
  Name = "your-name"

[outputs]
  home = [ "RSS", "HTML" ]
    
[outputFormats] 
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "feed"

[Params]
  AuthorHomepage = "your-home-page"
  BottomIntroduce = "Introduce1 <br/> Introduce2"
  Description = ""
  Subtitle = "subtitle"
  Weibo = ""
  WeiboID = 123
  Twitter = ""
  GitHub = ""
  Facebook = ""
  LinkIn = ""
  Imglogo = "img/logo.svg"
  AuthorImg = "img/author.jpg"
  DateFormat = "2006年01月02日"
  MonthFormat = "2006年01月"
  FancyBox = true
  CreativeCommons = true
  MathJax = false

  [Params.GoogleAnalytics]
    ID = ""

  [Params.Disqus]
    ShortName = ""

  [Params.Strings]
    Search = "搜索"
    PageNotFound = "你访问的页面不存在"
    ShowSideBar = "显示侧边栏"
    HideSideBar = "隐藏侧边栏"
    Categories = "分类"
    Archive = "归档"
    Tags = "标签"
    TagCloud = "标签云"
    Rss = "RSS 订阅"
    TableOfContents = "文章目录"

[Menu]
  [[Menu.Main]]
    Name = "首页"
    URL = "/"
    Weight = 1
  [[Menu.Main]]
    Name = "关于"
    URL = "/about"
    Weight = 2
